### ISSUE TITLE
Can't run the app

### ISSUE THREAD

**Issue by aliabbasjaffri** [Semantive/waveform-android#1]
I am trying to compile the application but it keeps on giving me the same error.

Information:Gradle tasks [:app:assembleDebug]
plugin name 'retrolambda' is deprecated and will be removed in the next release, please change to 'me.tatarka.retrolambda'
:app:preBuild UP-TO-DATE
:app:preDebugBuild UP-TO-DATE
:app:compileDebugNdk UP-TO-DATE
:app:checkDebugManifest
:app:preReleaseBuild UP-TO-DATE
:app:prepareComAndroidSupportAppcompatV72200Library UP-TO-DATE
:app:prepareComAndroidSupportSupportV42200Library UP-TO-DATE
:app:prepareDebugDependencies
:app:compileDebugAidl UP-TO-DATE
:app:compileDebugRenderscript UP-TO-DATE
:app:generateDebugBuildConfig UP-TO-DATE
:app:generateDebugAssets UP-TO-DATE
:app:mergeDebugAssets UP-TO-DATE
:app:generateDebugResValues UP-TO-DATE
:app:generateDebugResources UP-TO-DATE
:app:mergeDebugResources UP-TO-DATE
:app:processDebugManifest UP-TO-DATE
:app:processDebugResources UP-TO-DATE
:app:generateDebugSources UP-TO-DATE
:app:compileDebugJava
:app:patchAndroidJar FAILED
Error:Execution failed for task ':app:patchAndroidJar'.

> Retrolambda: null/jre/lib/rt.jar does not exist, make sure that the environment variable JAVA_HOME or JAVA8_HOME, or the gradle property retrolambda.jdk points to a valid version of java8.

Please provide an issue for it.
Thank you!

**Comment by aliabbasjaffri** [comment]
If i make additions to the build.gradle like in https://github.com/evant/gradle-retrolambda , the error becomes this...

Information:Gradle tasks [:app:assembleDebug]
:app:preBuild UP-TO-DATE
:app:preDebugBuild UP-TO-DATE
:app:compileDebugNdk UP-TO-DATE
:app:checkDebugManifest
:app:preReleaseBuild UP-TO-DATE
:app:prepareComAndroidSupportAppcompatV72200Library UP-TO-DATE
:app:prepareComAndroidSupportSupportV42200Library UP-TO-DATE
:app:prepareDebugDependencies
:app:compileDebugAidl UP-TO-DATE
:app:compileDebugRenderscript UP-TO-DATE
:app:generateDebugBuildConfig UP-TO-DATE
:app:generateDebugAssets UP-TO-DATE
:app:mergeDebugAssets UP-TO-DATE
:app:generateDebugResValues UP-TO-DATE
:app:generateDebugResources UP-TO-DATE
:app:mergeDebugResources UP-TO-DATE
:app:processDebugManifest UP-TO-DATE
:app:processDebugResources UP-TO-DATE
:app:generateDebugSources UP-TO-DATE
:app:compileDebugJava
An exception has occurred in the compiler (1.8.0_40). Please file a bug at the Java Developer Connection (http://java.sun.com/webapps/bugreport)  after checking the Bug Parade for duplicates. Include your program and the following diagnostic in your report.  Thank you.
com.sun.tools.javac.code.Symbol$CompletionFailure: class file for java.lang.invoke.MethodType not found
Error:Execution failed for task ':app:compileDebugJava'.

> Compilation failed; see the compiler error output for details.

Please provide a solution to this as soon as possible. Thank you!

**Comment by solitaire** [comment]
I don't know which OS you are running, but it looks like there is a problem with the JDK path. Under my Ubuntu 15.04 with Oracle JDK I have following environment variables set (they are defined in my .profile file):
- JAVA_HOME
- JAVA_7_HOME
- JAVA_8_HOME

and it builds without any problems. Unfortunately, I don't have access to other OS, but you may find this link useful, as it provides possible solutions to the problem you described: https://github.com/evant/gradle-retrolambda/issues/17

**Comment by aliabbasjaffri** [comment]
I was able to solve it. There is an issue with the build.gradle file. I tried to push the fix but there was an authentication error. I a posting the solution here.

//it starts from here.

buildscript
{
    repositories {
        mavenCentral()
    }

```
apply plugin: 'com.android.application' //or apply plugin: 'java'
apply plugin: 'me.tatarka.retrolambda'

dependencies {
    classpath 'me.tatarka:gradle-retrolambda:3.2.0'
}
```

}

// Required because retrolambda is on maven central
repositories {
    mavenCentral()
}

android {
    compileSdkVersion 22
    buildToolsVersion "21.1.2"

```
compileOptions {
    sourceCompatibility JavaVersion.VERSION_1_8
    targetCompatibility JavaVersion.VERSION_1_8
}

defaultConfig {
    applicationId "com.semantive.waveform.waveformandroid"
    minSdkVersion 16
    targetSdkVersion 22
    versionCode 1
    versionName "1.0"
}
buildTypes {
    release {
        minifyEnabled false
        proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
    }
}
```

}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'com.android.support:appcompat-v7:22.0.0'
}

**Comment by solitaire** [comment]
I updated .build files in commit https://github.com/Semantive/waveform-android/commit/43414397a21e41995ac1139f0098dc752cec0ea7
