### ISSUE TITLE
How to get the start and the end time?

### ISSUE THREAD

**Issue by bullheadandplato** [Semantive/waveform-android#18]
I reviewed the code but I'm unable to find the getStartTime or getEndTime method. I'm missing something or they simple don't exist?

**Comment by monxarat** [comment]
You can get it by way get from `mStartPos` and `mEndPos`. You must convert this value to seconds or milliseconds. Because of this value I pixel value.

```
int startTime = mWaveformView.pixelsToMillisecs(mStartPos);
int endTime = mWaveformView.pixelsToMillisecs(mEndPos);
```
