### ISSUE TITLE
Add your project in gradle repository

### ISSUE THREAD

**Issue by oximer** [Semantive/waveform-android#3]
Can you please add your project into a repository so that we can use

dependencies {
    compile 'com.semantive.waveform-android:app:1.0.0'
}

**Comment by solitaire** [comment]
You can now use waveform-android with gradle by adding flollowing lines to your `build.gradle` file:

``` gradle
repositories {
    maven { url "https://jitpack.io" }
}

dependencies {
    compile 'com.github.Semantive:waveform-android:v1.0'
}
```
