### ISSUE TITLE
Just display a WaveformView

### ISSUE THREAD

**Issue by svenoaks** [Semantive/waveform-android#6]
I just want to display a WaveformView, not attached to playing a file.

I call 

```
CheapSoundFile file = null;
        try
        {
            file = CheapSoundFile.create("/sdcard/malo.m4a", new CheapSoundFile.ProgressListener()
            {
                @Override
                public boolean reportProgress(double v)
                {
                    return true;
                }
            } );
        } catch (IOException e)
        {
            e.printStackTrace();
        }

        if (file != null) waveFormView.setSoundFile(file);
```

And it spins endlessly, somewhere in WaveFormView.onDraw();

What else do I have to do here?

**Comment by svenoaks** [comment]
If the line numbers are to be trusted its spinning endlessly here:

```
while (timecodeIntervalSecs / onePixelInSecs < 50) {
            timecodeIntervalSecs = 5.0 * factor;
            factor++;
        }
```

**Comment by svenoaks** [comment]
Ah I figured it out in case anyone else runs into the same thing. You have to setSoundFile after the View has been fully created, you can't just call it on onCreate() because it needs the real width and height of the view. Maybe attach a ViewTreeObserver.

**Comment by tutysathish** [comment]
Hi @svenoaks Did you implemented this concept for audio recording? Please share some guideline to implement the waveform without loading audio file (Like runtime value returned from Mediarecorder)
